### ISSUE TITLE
Sprites without TTL have a 0 ttl

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#53] opened 2019-01-22 17:33 UTC
This is a change that happened recently and it causes some bad behavior to sprites by default. I'd like to know the reasoning to perhaps find a better solution.

**Comment by straker** [comment] 2019-01-22 20:33
I knew this would haunt me :P I would love to come up with a better solution

Alright, so some history: 

So the v4 and before Sprite had a `ttl` of 0 mostly as a default for the object pool so it would register as not alive any time the pool needed a new object. The assumption was that anyone using the pool would set their own `ttl` when getting a sprite from the pool.

After writing https://medium.com/web-maker/making-asteroids-with-kontra-js-and-web-maker-95559d39b45f, I didn't like how any sprite was not alive by default. It made filtering an array of sprites and removing not alive ones difficult since you would have to go and add a `ttl=Infinity` to all sprites that weren't suppose to be removed. So in v5 I changed the `ttl` to default to Infinity, which made things easier.

However, that broke the object pool in #47 since now the sprite was always alive, and the `get` logic of the object pool would try to increase its size if all objects in it were alive. This resulted in an infinite loop and a pool of always `maxSize`.

So I revered `ttl` back to 0 in #49 to try to fix the problem, hoping it wouldn't case a new one. Guess I was wrong,

So the problem is that there is a conflict between wanting a sprite to always be alive by default, but providing sprites that aren't alive by default so the object pools size calculations work. The solution may be as simple as just defaulting any sprite created in the pool to `ttl=0`, but `ttl` technically isn't required for an object sprite, only having an `isAlive()` function to abstract it.

**Comment by BoldBigflank** [comment] 2019-01-22 21:51
https://github.com/straker/kontra/pull/54

Ok, I made sure that the pool works even with sprites that are alive by default, and put the sprite back to always alive by default. Looks like the pool.render and pool.update functions already used the `inUse` variable to iterate, so it doesn't render/update alive sprites that aren't yet being used, which is great.

I also had the create function return the sprite that was made.

**Comment by BoldBigflank** [comment] 2019-01-22 21:54
I don't think the pool is doing enough to reset the sprite when it is done and returned to the pool. that sprite object might have functions outside of its default that just stay there for the next time this is `create`d. Is that right? Does that need to be another Issue?

**Comment by straker** [comment] 2019-01-23 01:56
Closed by #54

**Closed** 2019-01-23 01:56 UTC
